INSERT INTO EMPLOYEE (ID, NAME) VALUES (1, 'SACHIN');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (2, 'SEHWAG');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (3, 'KOHLI');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (4, 'YUVARAJ');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (5, 'DHONI');