CREATE TABLE IF NOT EXISTS EMPLOYEE
        (
        ID NUMBER(10) NOT NULL PRIMARY KEY,
        NAME VARCHAR2(50) NOT NULL,
        );

create table BOOKINGS(ID serial, FIRST_NAME varchar(5) NOT NULL);